//! automations — the OS scheduled task behind Settings → Automations.
//!
//! One command, three actions, Windows-first:
//!   `invoke("manage_automation", { action: "register" | "remove" | "status",
//!     intervalMin, maxCostUsd, repoPath })`
//!   → `{ registered: bool, detail: string, nextRun: string | null }`
//!
//! Registration does NOT put the bash invocation on the `schtasks /Create`
//! command line. That line has a documented ~261 char limit and would need
//! triple-nested quoting (`cmd /C "set X=1&& "C:\Program Files\…\bash.exe"
//! -c "…"`) which a repo path containing a space does not survive. Instead we
//! write a tiny launcher — `<repo>\.zelari\gardener-task.cmd` — that exports
//! `ZELARI_MISSION_MAX_COST` and runs `bash <repo>/scripts/zelari-gardener.sh
//! <repo>`, and point the task at that file. Every register rewrites the
//! launcher, so the budget/interpreter always match the current Settings.
//!
//! The gardener itself is propose-only and budgets itself: quiet repo → exit 0
//! without spending anything (see scripts/zelari-gardener.sh).
//!
//! Deliberate limits (documented, not accidental):
//!   - the task runs as the logged-on user only (no /RU password dance, no
//!     elevation), so it is dormant while nobody is signed in — right for a
//!     desktop companion app;
//!   - removing the task leaves the launcher file on disk (regenerated on the
//!     next register; deleting files from the repo is not remove's job).

use serde_json::Value;
use std::path::Path;

#[cfg(windows)]
use serde_json::json;
#[cfg(windows)]
use std::fs;
#[cfg(windows)]
use std::path::PathBuf;
#[cfg(windows)]
use std::process::{Command, Stdio};

#[cfg(windows)]
use std::os::windows::process::CommandExt;

/// Name of the scheduled task (what `schtasks /Query /TN` looks for).
pub(crate) const TASK_NAME: &str = "ZelariGardener";

/// Mirror of desktopPrefs.gardenerIntervalMin (the UI clamps too).
const MIN_INTERVAL_MIN: u32 = 5;
const MAX_INTERVAL_MIN: u32 = 1440;
/// Mirror of desktopPrefs.gardenerMaxCostUsd.
const MIN_MAX_COST_USD: f64 = 0.5;
const MAX_MAX_COST_USD: f64 = 20.0;
const DEFAULT_MAX_COST_USD: f64 = 2.0;

/// Hide the console window for the short-lived schtasks / where helpers.
#[cfg(windows)]
const CREATE_NO_WINDOW: u32 = 0x0800_0000;

/// `..\scripts\zelari-gardener.sh` relative to the repo root.
const GARDENER_REL: &str = "scripts/zelari-gardener.sh";
/// Launcher written next to the gardener's own state (`.zelari/`).
const LAUNCHER_REL: &str = ".zelari/gardener-task.cmd";

/// Clamp the per-run budget to the window both sides agree on, 2 decimals.
/// Non-finite input falls back to the default (2 USD) instead of poisoning the
/// launcher with `NaN`.
fn clamp_cost(value: f64) -> f64 {
    let v = if value.is_finite() { value } else { DEFAULT_MAX_COST_USD };
    let clamped = v.clamp(MIN_MAX_COST_USD, MAX_MAX_COST_USD);
    (clamped * 100.0).round() / 100.0
}

/// Interval must be inside the window; a sick caller gets a typed error rather
/// than a task that hammers the repo every minute.
fn validate_interval(value: u32) -> Result<u32, String> {
    if (MIN_INTERVAL_MIN..=MAX_INTERVAL_MIN).contains(&value) {
        Ok(value)
    } else {
        Err(format!(
            "intervalMin must be between {MIN_INTERVAL_MIN} and {MAX_INTERVAL_MIN} minutes (got {value})."
        ))
    }
}

/// Body of the launcher `.cmd`. Pure so it can be unit-tested off-Windows:
/// quotes and the budget export live HERE, which is what keeps `/TR` short.
fn launcher_script(bash: &Path, script: &Path, repo: &Path, max_cost_usd: f64) -> String {
    format!(
        "@echo off\r\n\
         rem Zelari gardener launcher — regenerated by Settings → Automations.\r\n\
         set ZELARI_MISSION_MAX_COST={:.2}\r\n\
         \"{}\" \"{}\" \"{}\"\r\n",
        clamp_cost(max_cost_usd),
        bash.display(),
        script.display(),
        repo.display()
    )
}

/// `Next Run Time` column of `schtasks /Query /FO CSV /V`.
///
/// Position-based on purpose: the header and the date format are localized, the
/// column order is not. Pure so it can be unit-tested off-Windows.
fn parse_next_run(csv: &str) -> Option<String> {
    let mut lines = csv.lines().map(str::trim).filter(|l| !l.is_empty());
    lines.next()?; // header row
    let row = lines.next()?;
    let field = row.trim_matches('"').split("\",\"").nth(1)?;
    let cleaned = field.trim().trim_matches('"').to_string();
    if cleaned.is_empty() || cleaned.eq_ignore_ascii_case("N/A") {
        None
    } else {
        Some(cleaned)
    }
}

#[cfg(windows)]
fn hidden(cmd: &mut Command) -> &mut Command {
    cmd.creation_flags(CREATE_NO_WINDOW);
    cmd
}

#[cfg(windows)]
fn run_schtasks(args: &[&str]) -> Result<std::process::Output, String> {
    hidden(Command::new("schtasks").args(args))
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .map_err(|e| format!("Failed to run schtasks: {e}"))
}

#[cfg(windows)]
fn combined(out: &std::process::Output) -> String {
    let stdout = String::from_utf8_lossy(&out.stdout).trim().to_string();
    let stderr = String::from_utf8_lossy(&out.stderr).trim().to_string();
    match (stdout.is_empty(), stderr.is_empty()) {
        (false, false) => format!("{stdout} {stderr}"),
        (true, false) => stderr,
        (false, true) => stdout,
        (true, true) => format!("exit code {}", out.status.code().unwrap_or(-1)),
    }
}

/// Exit code only — "not registered" is by far the usual non-zero here, and the
/// message text is localized.
#[cfg(windows)]
fn is_registered() -> bool {
    matches!(run_schtasks(&["/Query", "/TN", TASK_NAME]), Ok(out) if out.status.success())
}

/// Find a bash interpreter that can run the gardener script.
#[cfg(windows)]
fn find_bash() -> Result<PathBuf, String> {
    let fixed = [
        r"C:\Program Files\Git\bin\bash.exe",
        r"C:\Program Files (x86)\Git\bin\bash.exe",
    ];
    for candidate in fixed {
        let path = PathBuf::from(candidate);
        if path.is_file() {
            return Ok(path);
        }
    }
    if let Ok(out) = hidden(Command::new("where").arg("bash"))
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .output()
    {
        if out.status.success() {
            if let Some(line) = String::from_utf8_lossy(&out.stdout)
                .lines()
                .map(str::trim)
                .find(|l| !l.is_empty())
            {
                let path = PathBuf::from(line);
                if path.is_file() {
                    return Ok(path);
                }
            }
        }
    }
    Err(
        "Git Bash not found — install Git for Windows, or put bash.exe on PATH. \
         (Checked C:\\Program Files\\Git\\bin\\bash.exe, C:\\Program Files (x86)\\Git\\bin\\bash.exe and `where bash`.)"
            .to_string(),
    )
}

#[cfg(windows)]
fn status() -> Result<Value, String> {
    let out = run_schtasks(&["/Query", "/TN", TASK_NAME, "/FO", "CSV", "/V"])?;
    if !out.status.success() {
        let code = out.status.code().unwrap_or(-1);
        return Ok(json!({
            "registered": false,
            "detail": format!("Not registered (schtasks /Query exit code {code})."),
            "nextRun": Value::Null,
        }));
    }
    let next = parse_next_run(&String::from_utf8_lossy(&out.stdout));
    let detail = match &next {
        Some(t) => format!("Registered — next run {t}."),
        None => "Registered (Task Scheduler reported no next run time).".to_string(),
    };
    Ok(json!({ "registered": true, "detail": detail, "nextRun": next }))
}

#[cfg(windows)]
fn register(interval_min: u32, max_cost_usd: f64, repo_path: &str) -> Result<Value, String> {
    let interval = validate_interval(interval_min)?;
    let cost = clamp_cost(max_cost_usd);

    let repo = repo_path.trim();
    if repo.is_empty() {
        return Err("No workspace folder — open the zelari-code repo before registering.".to_string());
    }
    let repo = PathBuf::from(repo);
    if !repo.is_dir() {
        return Err(format!("Workspace folder not found: {}", repo.display()));
    }

    let script = repo.join(GARDENER_REL);
    if !script.is_file() {
        return Err(format!(
            "Gardener script not found at {} — open the zelari-code repository as the workspace, then register.",
            script.display()
        ));
    }

    let bash = find_bash()?;
    let launcher = repo.join(LAUNCHER_REL);
    if let Some(parent) = launcher.parent() {
        fs::create_dir_all(parent)
            .map_err(|e| format!("Could not create {}: {e}", parent.display()))?;
    }
    fs::write(&launcher, launcher_script(&bash, &script, &repo, cost))
        .map_err(|e| format!("Could not write {}: {e}", launcher.display()))?;

    let tr = format!("\"{}\"", launcher.display());
    let minutes = interval.to_string();
    let out = run_schtasks(&[
        "/Create", "/TN", TASK_NAME, "/SC", "MINUTE", "/MO", &minutes, "/F", "/TR", &tr,
    ])?;
    if !out.status.success() {
        return Err(format!("schtasks /Create failed: {}", combined(&out)));
    }

    let mut value = status()?;
    value["detail"] = json!(format!(
        "Registered — every {interval} min, budget cap ${cost:.2} per run (launcher: {}).",
        launcher.display()
    ));
    Ok(value)
}

#[cfg(windows)]
fn remove() -> Result<Value, String> {
    if !is_registered() {
        return Ok(json!({
            "registered": false,
            "detail": "Not registered — nothing to remove.",
            "nextRun": Value::Null,
        }));
    }
    let out = run_schtasks(&["/Delete", "/TN", TASK_NAME, "/F"])?;
    if !out.status.success() {
        let message = combined(&out);
        // Raced with something else deleting it: gone is gone.
        if message.to_ascii_lowercase().contains("cannot find") {
            return Ok(json!({
                "registered": false,
                "detail": "Removed (already gone).",
                "nextRun": Value::Null,
            }));
        }
        return Err(format!("schtasks /Delete failed: {message}"));
    }
    Ok(json!({
        "registered": false,
        "detail": "Removed — the task no longer runs.",
        "nextRun": Value::Null,
    }))
}

#[tauri::command]
pub fn manage_automation(
    action: String,
    interval_min: u32,
    max_cost_usd: f64,
    repo_path: String,
) -> Result<Value, String> {
    #[cfg(not(windows))]
    {
        let _ = (action, interval_min, max_cost_usd, repo_path);
        Err("Scheduled automations use Windows Task Scheduler (schtasks); this build cannot register them.".to_string())
    }
    #[cfg(windows)]
    {
        match action.trim().to_ascii_lowercase().as_str() {
            "register" => register(interval_min, max_cost_usd, &repo_path),
            "remove" => remove(),
            "status" => status(),
            other => Err(format!(
                "Unknown automation action '{other}' (expected register, remove or status)."
            )),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn clamp_cost_holds_the_agreed_window() {
        assert_eq!(clamp_cost(2.0), 2.0);
        assert_eq!(clamp_cost(0.0), MIN_MAX_COST_USD);
        assert_eq!(clamp_cost(999.0), MAX_MAX_COST_USD);
        assert_eq!(clamp_cost(1.234), 1.23);
        assert_eq!(clamp_cost(f64::NAN), DEFAULT_MAX_COST_USD);
    }

    #[test]
    fn validate_interval_rejects_out_of_window() {
        assert_eq!(validate_interval(30).unwrap(), 30);
        assert_eq!(validate_interval(MIN_INTERVAL_MIN).unwrap(), MIN_INTERVAL_MIN);
        assert_eq!(validate_interval(MAX_INTERVAL_MIN).unwrap(), MAX_INTERVAL_MIN);
        assert!(validate_interval(0).is_err());
        assert!(validate_interval(MAX_INTERVAL_MIN + 1).is_err());
    }

    #[test]
    fn launcher_carries_budget_and_quoted_paths() {
        let body = launcher_script(
            Path::new(r"C:\Program Files\Git\bin\bash.exe"),
            Path::new(r"Z:\repo\scripts/zelari-gardener.sh"),
            Path::new(r"Z:\my repo"),
            2.5,
        );
        assert!(body.contains("@echo off"));
        assert!(body.contains("set ZELARI_MISSION_MAX_COST=2.50"));
        assert!(body.contains("\"C:\\Program Files\\Git\\bin\\bash.exe\""));
        assert!(body.contains("\"Z:\\repo\\scripts/zelari-gardener.sh\""));
        // The repo path is quoted, so a space cannot split it.
        assert!(body.contains("\"Z:\\my repo\""));
        // Clamped even when the caller asks for more than the cap.
        assert!(launcher_script(
            Path::new("bash"),
            Path::new("s.sh"),
            Path::new("r"),
            500.0
        )
        .contains("set ZELARI_MISSION_MAX_COST=20.00"));
    }

    #[test]
    fn launcher_stays_well_under_the_schtasks_tr_limit() {
        // Worst realistic case: long repo path inside Program Files.
        let launcher = Path::new(
            r"C:\Program Files\Zelari Code Examples\zelari-code\.zelari\gardener-task.cmd",
        );
        let tr = format!("\"{}\"", launcher.display());
        assert!(tr.len() < 261, "/TR would be {} chars", tr.len());
    }

    #[test]
    fn parse_next_run_reads_the_csv_column_and_tolerates_junk() {
        let csv = "\"TaskName\",\"Next Run Time\",\"Status\"\r\n\
                   \"\\ZelariGardener\",\"12/09/2026 10:30:00\",\"Ready\"\r\n";
        assert_eq!(
            parse_next_run(csv).as_deref(),
            Some("12/09/2026 10:30:00")
        );
        let none = "\"TaskName\",\"Next Run Time\"\r\n\"\\ZelariGardener\",\"N/A\"\r\n";
        assert_eq!(parse_next_run(none), None);
        assert_eq!(parse_next_run(""), None);
        assert_eq!(parse_next_run("\"only a header\"\r\n"), None);
    }
}
