/**
 * councilCost — per-member cost tracking for council runs (Task I.1, v3-I).
 *
 * Accumulates `MemberCost` records as each member of the council completes.
 * Side-effect free and deterministic so it can be unit-tested without
 * filesystem or network. The actual persistence / event emission is the
 * caller's job (see `runCouncilPure` in `councilApi.ts` which feeds this
 * helper and emits `member_cost` BrainEvents downstream).
 *
 * Cost fields captured per member:
 *   - promptTokens / completionTokens / totalTokens
 *   - durationMs (wall-clock)
 *   - toolCalls (count of tool_execution_start events)
 *   - errored (boolean)
 *
 * @see docs/plans/2026-06-29-anathema-coder-v3-I.md (I.1)
 */

import type { UsageBreakdown } from '../shared/events.js';

export interface MemberCost {
  /** Member id (e.g. 'charont', 'nettun', 'minos', 'lucifer'). */
  memberId: string;
  /** Human-readable name (e.g. 'Caronte'). */
  name: string;
  /** Tokens in the prompt. Default 0 when the provider does not report usage. */
  promptTokens: number;
  /** Tokens generated by the assistant. Default 0. */
  completionTokens: number;
  /** Convenience: promptTokens + completionTokens. */
  totalTokens: number;
  /** Wall-clock duration of this member's run in milliseconds. */
  durationMs: number;
  /** Number of tool_execution_start events emitted by this member. */
  toolCalls: number;
  /** True if the member's run threw an error. */
  errored: boolean;
}

export interface RecordInput {
  memberId: string;
  name: string;
  usage?: UsageBreakdown | null;
  durationMs: number;
  toolCalls?: number;
  errored?: boolean;
}

export interface MemberCostTrackerOptions {
  /** Optional `now()` for tests (default `Date.now`). */
  now?: () => number;
}

export class MemberCostTracker {
  private readonly costs = new Map<string, MemberCost>();
  private readonly now: () => number;

  constructor(options: MemberCostTrackerOptions = {}) {
    this.now = options.now ?? Date.now;
  }

  /**
   * Record cost for one member. If the same memberId is recorded twice
   * (shouldn't happen in practice — council members are unique), the
   * second call REPLACES the first. This makes accidental double-count
   * visible: the caller sees the latest numbers rather than a silent sum.
   */
  record(input: RecordInput): MemberCost {
    const usage = input.usage ?? null;
    const prompt = usage?.promptTokens ?? 0;
    const completion = usage?.completionTokens ?? 0;
    const cost: MemberCost = {
      memberId: input.memberId,
      name: input.name,
      promptTokens: prompt,
      completionTokens: completion,
      totalTokens: usage?.totalTokens ?? prompt + completion,
      durationMs: Math.max(0, Math.round(input.durationMs)),
      toolCalls: input.toolCalls ?? 0,
      errored: input.errored ?? false,
    };
    this.costs.set(input.memberId, cost);
    return cost;
  }

  /** Snapshot of all recorded costs, in insertion order. */
  finalize(): MemberCost[] {
    return Array.from(this.costs.values());
  }

  /** Total tokens across all members (prompt + completion). */
  totalTokens(): number {
    let t = 0;
    for (const c of this.costs.values()) t += c.totalTokens;
    return t;
  }

  /** Total wall-clock time across all members. Note: this is sum-of-mems,
   *  not elapsed council time (specialists run sequentially). */
  totalDurationMs(): number {
    let t = 0;
    for (const c of this.costs.values()) t += c.durationMs;
    return t;
  }

  /**
   * JSON-serializable snapshot of the tracker state, including a generated
   * `ts` field. Useful for persistence and event payloads.
   */
  toJSON(): { ts: number; costs: MemberCost[] } {
    return { ts: this.now(), costs: this.finalize() };
  }

  /** Reconstruct a tracker from a JSON snapshot. Used by tests + persistence. */
  static fromJSON(
    json: { ts?: number; costs: MemberCost[] },
    options: MemberCostTrackerOptions = {},
  ): MemberCostTracker {
    const t = new MemberCostTracker(options);
    for (const c of json.costs) t.costs.set(c.memberId, c);
    return t;
  }
}
