/**
 * automations/types.ts — schemas + inferred types for the Automations Registry.
 *
 * Contract: ADR-0037 (Automations Registry e social_post). F0+F1 define the
 * on-disk shapes only; the social_post runner itself lands in F2. Zod v4,
 * node stdlib only — no runtime dependency beyond `zod`.
 *
 * On-disk layout (see registry.ts):
 *   .zelari/automations/index.json             { version, automations: [{id,enabled}] }
 *   .zelari/automations/<id>.json              AutomationSpec
 *   .zelari/automations/runs/<id>/<runId>.json AutomationRun
 */
import { z } from 'zod';

/** Automation id shape. `gardener` is the reserved back-compat id. */
export const AUTOMATION_ID_RE = /^[a-z0-9][a-z0-9-]{1,39}$/;

/** The legacy Gardener job id — never deletable, migrated from prefs in F0. */
export const RESERVED_AUTOMATION_ID = 'gardener';

/** Job families. `gardener` is propose-only; `social_post` lands in F2. */
export const AutomationKindSchema = z.enum(['gardener', 'social_post']);
export type AutomationKind = z.infer<typeof AutomationKindSchema>;

/**
 * Schedule. The trigger modes are MUTUALLY EXCLUSIVE — at most one of:
 *   intervalMin — every N minutes (materialized since F1)
 *   cron        — a cron expression (materialization lands in F2)
 *   atLogon     — run once at OS logon/boot (`atLogon === true`)
 * A spec may omit the trigger entirely (a manual/legacy schedule, e.g. a
 * social_post only run on demand): that stays VALID for back-compat, so the
 * rule is "at most one", never "exactly one". `timezone` is orthogonal.
 */
export const ScheduleSchema = z
  .object({
    intervalMin: z.number().int().min(5).max(1440).optional(),
    cron: z.string().optional(),
    atLogon: z.boolean().optional(),
    timezone: z.string().default('Europe/Rome'),
  })
  .refine(
    (s) => [s.intervalMin !== undefined, !!s.cron, s.atLogon === true].filter(Boolean).length <= 1,
    { message: 'schedule: at most one of intervalMin | cron | atLogon may be set' },
  );
export type Schedule = z.infer<typeof ScheduleSchema>;

/** Per-run cost guardrail (USD). */
export const BudgetSchema = z.object({
  maxCostUsd: z.number().default(1),
});
export type Budget = z.infer<typeof BudgetSchema>;

/**
 * Provider+model reference for a task. `id` is the model name (required);
 * `provider` defaults to the active provider when absent. Kind-agnostic: an
 * automation may pick a different model per task (e.g. a cheap model for a
 * social draft, a stronger one for gardener analysis).
 */
export const ModelRefSchema = z.object({
  provider: z.string().min(1).optional(),
  id: z.string().min(1),
});
export type ModelRef = z.infer<typeof ModelRefSchema>;

/** Optional media attachment for a social post. */
export const SocialMediaSchema = z.object({
  paths: z.array(z.string()),
  alt: z.array(z.string()).optional(),
});
export type SocialMedia = z.infer<typeof SocialMediaSchema>;

/** `social_post` job body (F2 runner). */
export const SocialPostSpecSchema = z.object({
  channels: z.array(z.string()).min(1),
  topicOrBrief: z.string(),
  /**
   * Free-form drafting instructions for the LLM. If `prompt` names an existing
   * `.md`/`.txt` file (resolved against the project root) the file content is
   * used instead — the same convention as `topicOrBrief`. ABSENT ⇒ the static
   * draft (today's behavior, no LLM). PRESENT ⇒ the post is generated by the
   * LLM using the automation's `model` (or the active provider/model default).
   * The tokens `{{brief}}` / `{{topic}}` are replaced by the resolved brief;
   * when neither is present the brief is appended as context.
   */
  prompt: z.string().optional(),
  /**
   * Fresh-research directive: when set (and `prompt` is set) the runner runs a
   * keyless web search BEFORE the LLM call and appends the hits to the user
   * message as context (recurring posts stay fresh). A search failure degrades
   * to a `research_failed:*` warning — the draft still needs human approval.
   */
  researchQuery: z.string().max(600).optional(),
  /** Cap on the search hits fed into the prompt (1–10, default 5). */
  researchMaxResults: z.number().int().min(1).max(10).optional(),
  tone: z.string().optional(),
  media: SocialMediaSchema.optional(),
  requireApproval: z.boolean().default(true),
  /**
   * How an approved draft is delivered (F3.2). Absent ⇒ 'dry-run' (safe default:
   * no silent real posting; the runner normalizes absent → 'dry-run').
   */
  publishMode: z.enum(['dry-run', 'browser']).optional(),
  /** Minutes a draft stays pending before it expires (F2; min 5). */
  approvalTtlMin: z.number().int().min(5).default(1440),
  maxPostsPerDay: z.number().int().positive().optional(),
  utm: z.record(z.string(), z.string()).optional(),
  website: z
    .object({
      endpoint: z.string().min(1),
      method: z.literal('POST').optional(),
      bodyTemplate: z.string().optional(),
    })
    .optional(),
});
export type SocialPostSpec = z.infer<typeof SocialPostSpecSchema>;

/** A single automation definition (the registry's source of truth). */
export const AutomationSpecSchema = z.object({
  id: z.string().regex(AUTOMATION_ID_RE),
  name: z.string(),
  enabled: z.boolean().default(false),
  kind: AutomationKindSchema,
  schedule: ScheduleSchema.default({ timezone: 'Europe/Rome' }),
  budget: BudgetSchema.default({ maxCostUsd: 1 }),
  /**
   * Per-task model selection. ABSENT ⇒ the active provider/model defaults are
   * used (or the provider built-in when the kind does not call an LLM).
   */
  model: ModelRefSchema.optional(),
  /** Free-form gardener knobs (reserved for future use). */
  gardener: z.record(z.string(), z.unknown()).optional(),
  social_post: SocialPostSpecSchema.optional(),
});
export type AutomationSpec = z.infer<typeof AutomationSpecSchema>;

/** run lifecycle states. */
export const RunStatusSchema = z.enum([
  'drafting',
  'awaiting_approval',
  'publishing',
  'completed',
  'failed',
  'skipped',
  'relogin_required',
]);
export type RunStatus = z.infer<typeof RunStatusSchema>;

/** Exit-code contract: 0 ok, 1 error, 4 unproven/needs-attention (P1). */
export const RunExitCodeSchema = z.union([z.literal(0), z.literal(1), z.literal(4)]);
export type RunExitCode = z.infer<typeof RunExitCodeSchema>;

/** One human approval decision on a draft. */
export const RunApprovalSchema = z.object({
  at: z.string(),
  decision: z.enum(['allow', 'deny', 'edit']),
  editedText: z.string().optional(),
});
export type RunApproval = z.infer<typeof RunApprovalSchema>;

/** One channel's publish outcome. `completed` requires ok:true AND a url/postId. */
export const RunPostSchema = z.object({
  channel: z.string(),
  ok: z.boolean(),
  postId: z.string().optional(),
  url: z.string().optional(),
  /** true when nothing was sent to the network (F2 always true). */
  dryRun: z.boolean().optional(),
  /** Evidence screenshot path captured by the F3.2 browser publisher. */
  screenshot: z.string().optional(),
  error: z.string().optional(),
});
export type RunPost = z.infer<typeof RunPostSchema>;

/** One automation run — the evidence record persisted under runs/<id>/. */
export const AutomationRunSchema = z.object({
  runId: z.string(),
  automationId: z.string(),
  /** ISO-8601 timestamp (kept a plain string to stay tolerant on read). */
  startedAt: z.string(),
  finishedAt: z.string().optional(),
  /** When a pending approval expires (F2 social_post). */
  expiresAt: z.string().optional(),
  status: RunStatusSchema,
  /** Machine-readable cause for a skipped/failed run (e.g. max_posts_per_day). */
  reason: z.string().optional(),
  draft: z
    .object({
      text: z.string(),
      media: z.array(z.string()).optional(),
      warnings: z.array(z.string()).optional(),
      /** How the draft was produced: the static brief or an LLM call. */
      generatedBy: z
        .object({
          source: z.enum(['static', 'llm']),
          provider: z.string().optional(),
          model: z.string().optional(),
        })
        .optional(),
        /** Fresh web research executed before the LLM call (`researchQuery`). */
        research: z
          .object({ query: z.string(), provider: z.string(), hits: z.number().int() })
          .optional(),
    })
    .optional(),
  approvals: z.array(RunApprovalSchema).optional(),
  posts: z.array(RunPostSchema).optional(),
  costUsd: z.number().optional(),
  exitCode: RunExitCodeSchema,
});
export type AutomationRun = z.infer<typeof AutomationRunSchema>;

/** One row of index.json. */
export interface AutomationIndexEntry {
  id: string;
  enabled: boolean;
}

/** index.json root. */
export interface RegistryIndex {
  version: 1;
  automations: AutomationIndexEntry[];
}

/** Compact list projection used by `zelari-code automation list`. */
export interface AutomationListItem {
  id: string;
  enabled: boolean;
  name: string;
  kind: AutomationKind;
}
